### ISSUE TITLE
Too soon to post issues?

### ISSUE THREAD

**Issue by PlutoX86** [OpenEmu/Reicast-Core#3]
I've noticed some strange behaviour when more than one player is enabled (ReicastGameCore.mm), player 2(?) presses buttons randomly, until they've been manually pressed by a keyboard or a gamepad. Also, the "reset" button in the menu doesn't work. 

I'm sure my 50cs are obsolete since everything is still WIP. But thanks anyway for.. everything. :)

**Comment by duckey77** [comment]
It is too soon, but try out the latest code.  Many things are fixed.  Only one controller is configured for use in the core (Reicast has an issue that Flyinghead is aware of)
