### ISSUE TITLE
Reicast issue

### ISSUE THREAD

**Issue by leBriscard** [OpenEmu/Reicast-Core#4]
Hello everyone !

I tried to compile by myself a reicast core but I didn't manage to do it. I don't know if its because of catalina or any other reason  but anyway I don't know nothing about that. I would like to know if its possible to download the reicast core somewhere, it would be great.

Thanks for you work, OpenEmu is a really cool device !!!!!!

**Comment by clobber** [comment]
Sorry, experimental and WIP core ports are strictly unsupported.
